//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CABIProgram.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CABIProduct
    {
        public int ID { get; set; }
        public int ThemeID { get; set; }
        public string NewTitle { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Contents { get; set; }
        public string Color { get; set; }
        public Nullable<bool> TopRecommend { get; set; }
        public string SizeInfo { get; set; }
        public string Scene { get; set; }
        public string ListImg { get; set; }
        public string ImgList { get; set; }
        public Nullable<int> ImgListTopIndex { get; set; }
        public Nullable<int> ProductClickNum { get; set; }
        public Nullable<int> CollectionNum { get; set; }
        public Nullable<int> OrderNum { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
        public Nullable<int> Desplay { get; set; }
        public Nullable<int> AllDesplay { get; set; }
        public Nullable<bool> IsLocked { get; set; }
        public string Remark { get; set; }
        public Nullable<int> TopDesplay { get; set; }
        public string Discribe { get; set; }
        public string CollectionImg { get; set; }
        public Nullable<int> ShareNum { get; set; }
        public byte[] TimeStamp { get; set; }
        public string ContentIMGList { get; set; }
        public string DesignConcept { get; set; }
        public string ClothInfo { get; set; }
    
        public virtual TitleType TitleType { get; set; }
    }
}
